# Generated by Django 3.2.5 on 2021-08-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
        migrations.AlterModelTable(
            name='datasheet',
            table='datasheet',
        ),
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
        migrations.AlterModelTable(
            name='profession',
            table='profession',
        ),
    ]
