# Generated by Django 3.2.5 on 2021-08-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest1', '0002_auto_20210802_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
